// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDNOK8NiMNWk_YvnYWt31K3FW_97ql_lmM',
    appId: '1:971310272861:web:25fc786b3d5d1806b058b4',
    messagingSenderId: '971310272861',
    projectId: 'first-app-d6c86',
    authDomain: 'first-app-d6c86.firebaseapp.com',
    storageBucket: 'first-app-d6c86.firebasestorage.app',
    measurementId: 'G-QP8SVBC12D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBoafKKclg-U6AGdg6I7cNVvtGt6gqslWE',
    appId: '1:971310272861:android:aac03a489103e151b058b4',
    messagingSenderId: '971310272861',
    projectId: 'first-app-d6c86',
    storageBucket: 'first-app-d6c86.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDzjQk9UZkJ3kHHsnzWsGatxbu1PxAIZT0',
    appId: '1:971310272861:ios:3b61043f10371abfb058b4',
    messagingSenderId: '971310272861',
    projectId: 'first-app-d6c86',
    storageBucket: 'first-app-d6c86.firebasestorage.app',
    iosBundleId: 'com.example.daftarBelanja',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDzjQk9UZkJ3kHHsnzWsGatxbu1PxAIZT0',
    appId: '1:971310272861:ios:3b61043f10371abfb058b4',
    messagingSenderId: '971310272861',
    projectId: 'first-app-d6c86',
    storageBucket: 'first-app-d6c86.firebasestorage.app',
    iosBundleId: 'com.example.daftarBelanja',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDNOK8NiMNWk_YvnYWt31K3FW_97ql_lmM',
    appId: '1:971310272861:web:08102f292493d0f0b058b4',
    messagingSenderId: '971310272861',
    projectId: 'first-app-d6c86',
    authDomain: 'first-app-d6c86.firebaseapp.com',
    storageBucket: 'first-app-d6c86.firebasestorage.app',
    measurementId: 'G-4XEP5YMGW6',
  );
}
